services:
  payload-3-bun-template:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/payload-3-bun-template/Dockerfile
      args:
        PROJECT: '@dappermountain/payload-3-bun-template'
        PROJECT_PATH: 'apps/payload-3-bun-template'
    command: sh -c 'bun install && bun dev'
    env_file:
      - apps/payload-3-bun-template/.env
    ports:
      - 3001:3000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    restart: unless-stopped
    image: timescale/timescaledb:latest-pg16
    healthcheck:
      test: ['CMD-SHELL', 'g_isready -U ${DATABASE_USER:-payload} -d ${DATABASE_NAME:-payload}']
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-payload}
      POSTGRES_USER: ${DATABASE_USER:-payload}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-payload}
    ports:
      - 5442:5432
    volumes:
      - data:/var/lib/postgresql/data

  db-test:
    restart: unless-stopped
    image: timescale/timescaledb:latest-pg16
    healthcheck:
      test: ['CMD-SHELL', 'g_isready -U ${DATABASE_USER:-payload} -d ${DATABASE_NAME:-payload}']
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-payload}
      POSTGRES_USER: ${DATABASE_USER:-payload}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-payload}
    ports:
      - 5443:5432
    volumes:
      - data_test:/var/lib/postgresql/data
volumes:
  data:
  data_test:
