# fly.toml app configuration file generated for payload-3-bun-template-production on 2025-02-27T21:33:19-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'payload-3-bun-template-production'
primary_region = 'lax'

[build]
  dockerfile = './Dockerfile'

  [build.args]
    PROJECT = '@dappermountain/payload-3-bun-template'
    PROJECT_PATH = 'apps/payload-3-bun-template'

[deploy]
  strategy = 'rolling'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  size = 'shared-cpu-2x'
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
