export { budgetsAccess } from './budgets'
export { categoriesAccess } from './categories'
export { categoryGroupsAccess } from './categoryGroups'
export { workspaceContentAccess, workspaceContentReadAccess } from './workspaceContent'
export { workspacesAccess, workspacesReadAccess } from './workspaces'
export { usersAccess } from './users'
