name: Deploy Payload 3 Bun Template Review App

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    paths:
      - apps/payload-3-bun-template/**

jobs:
  deploy:
    name: Deploy Payload 3 Bun Template Review App
    runs-on: ubuntu-latest
    permissions: write-all
    environment:
      name: review
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Fly.io app name
        id: name
        run: |
          echo "name=payload-3-bun-template-review-${{ github.event.number }}" >> $GITHUB_OUTPUT

      - name: Set Fly.io url
        id: url
        run: |
          echo "url=https://${{ steps.name.outputs.name }}.fly.dev" >> $GITHUB_OUTPUT

      - name: Deploy review app to Fly.io
        id: deploy
        uses: superfly/fly-pr-review-apps@1.3.0
        with:
          org: ORG_NAME
          name: payload-3-bun-template-review-${{ github.event.number }}
          config: ${{ github.workspace }}/apps/payload-3-bun-template/fly.toml
          postgres: DB_NAME
          memory: 1024
          secrets: ${{ steps.format-secrets.outputs.variables }}
        env:
          FLY_API_TOKEN: ${{ steps.doppler.outputs.FLY_API_TOKEN }}
