/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    workspaces: Workspace;
    units: Unit;
    budgets: Budget;
    'category-groups': CategoryGroup;
    categories: Category;
    accounts: Account;
    'journal-entries': JournalEntry;
    'journal-lines': JournalLine;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    workspaces: WorkspacesSelect<false> | WorkspacesSelect<true>;
    units: UnitsSelect<false> | UnitsSelect<true>;
    budgets: BudgetsSelect<false> | BudgetsSelect<true>;
    'category-groups': CategoryGroupsSelect<false> | CategoryGroupsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    'journal-entries': JournalEntriesSelect<false> | JournalEntriesSelect<true>;
    'journal-lines': JournalLinesSelect<false> | JournalLinesSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  fullName?: string | null;
  roles?: ('SYSTEM_ADMIN' | 'SYSTEM_USER')[] | null;
  workspaces?:
    | {
        workspace: string | Workspace;
        roles: ('WORKSPACE_ADMIN' | 'WORKSPACE_USER')[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workspaces".
 */
export interface Workspace {
  id: string;
  name: string;
  description: string;
  domain: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units".
 */
export interface Unit {
  id: string;
  workspace?: (string | null) | Workspace;
  /**
   * ISO 4217 code for currency (e.g. USD) or a stable identifier for other units.
   */
  code: string;
  name: string;
  kind: 'currency' | 'commodity' | 'other';
  decimalPlaces: number;
  symbol?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "budgets".
 */
export interface Budget {
  id: string;
  workspace?: (string | null) | Workspace;
  name: string;
  /**
   * Primary budget for this household when none is selected.
   */
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category-groups".
 */
export interface CategoryGroup {
  id: string;
  workspace?: (string | null) | Workspace;
  name: string;
  /**
   * Credit card payment groups are auto-created when a credit card account is added.
   */
  kind: 'income' | 'expense' | 'credit_card_payments';
  sortOrder?: number | null;
  budget: string | Budget;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  workspace?: (string | null) | Workspace;
  name: string;
  /**
   * Single emoji shown in the category list.
   */
  emoji?: string | null;
  purpose: 'income' | 'spending' | 'credit_card_payment';
  /**
   * Seeded catalog entry; user may customize or hide later.
   */
  isSystemDefault?: boolean | null;
  sortOrder?: number | null;
  categoryGroup: string | CategoryGroup;
  /**
   * Denormalized for queries; must match the selected group’s budget.
   */
  budget: string | Budget;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: string;
  workspace?: (string | null) | Workspace;
  name: string;
  classification: 'asset' | 'liability' | 'equity' | 'income' | 'expense';
  subtype: 'checking' | 'savings' | 'cash' | 'credit_card' | 'loan' | 'holding' | 'other';
  unit: string | Unit;
  /**
   * Payment envelope for credit card accounts only.
   */
  category?: (string | null) | Category;
  isOnBudget?: boolean | null;
  budget: string | Budget;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-entries".
 */
export interface JournalEntry {
  id: string;
  workspace?: (string | null) | Workspace;
  budget: string | Budget;
  date: string;
  memo?: string | null;
  type: 'transaction' | 'transfer' | 'adjustment' | 'opening_balance';
  status: 'draft' | 'posted' | 'void';
  /**
   * Links the two sides of a transfer when posted separately.
   */
  transferGroupId?: string | null;
  /**
   * When this entry voids another posted entry.
   */
  voidOf?: (string | null) | JournalEntry;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-lines".
 */
export interface JournalLine {
  id: string;
  workspace?: (string | null) | Workspace;
  entry: string | JournalEntry;
  account: string | Account;
  category?: (string | null) | Category;
  /**
   * Signed amount in the line unit (negative = credit, positive = debit).
   */
  amount: number;
  unit: string | Unit;
  sortOrder?: number | null;
  /**
   * Amount in budget reporting currency when FX applies.
   */
  reportingAmount?: number | null;
  /**
   * Exchange rate applied for reportingAmount.
   */
  fxRate?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: string;
  /**
   * The user that the API key is associated with.
   */
  user: string | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  users?: {
    /**
     * Allow clients to find users.
     */
    find?: boolean | null;
    /**
     * Allow clients to create users.
     */
    create?: boolean | null;
    /**
     * Allow clients to update users.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete users.
     */
    delete?: boolean | null;
  };
  workspaces?: {
    /**
     * Allow clients to find workspaces.
     */
    find?: boolean | null;
    /**
     * Allow clients to create workspaces.
     */
    create?: boolean | null;
    /**
     * Allow clients to update workspaces.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete workspaces.
     */
    delete?: boolean | null;
  };
  budgets?: {
    /**
     * Allow clients to find budgets.
     */
    find?: boolean | null;
    /**
     * Allow clients to create budgets.
     */
    create?: boolean | null;
    /**
     * Allow clients to update budgets.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete budgets.
     */
    delete?: boolean | null;
  };
  categoryGroups?: {
    /**
     * Allow clients to find category-groups.
     */
    find?: boolean | null;
    /**
     * Allow clients to create category-groups.
     */
    create?: boolean | null;
    /**
     * Allow clients to update category-groups.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete category-groups.
     */
    delete?: boolean | null;
  };
  categories?: {
    /**
     * Allow clients to find categories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create categories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update categories.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete categories.
     */
    delete?: boolean | null;
  };
  units?: {
    /**
     * Allow clients to find units.
     */
    find?: boolean | null;
    /**
     * Allow clients to create units.
     */
    create?: boolean | null;
    /**
     * Allow clients to update units.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete units.
     */
    delete?: boolean | null;
  };
  accounts?: {
    /**
     * Allow clients to find accounts.
     */
    find?: boolean | null;
    /**
     * Allow clients to create accounts.
     */
    create?: boolean | null;
    /**
     * Allow clients to update accounts.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete accounts.
     */
    delete?: boolean | null;
  };
  journalEntries?: {
    /**
     * Allow clients to find journal-entries.
     */
    find?: boolean | null;
    /**
     * Allow clients to create journal-entries.
     */
    create?: boolean | null;
    /**
     * Allow clients to update journal-entries.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete journal-entries.
     */
    delete?: boolean | null;
  };
  journalLines?: {
    /**
     * Allow clients to find journal-lines.
     */
    find?: boolean | null;
    /**
     * Allow clients to create journal-lines.
     */
    create?: boolean | null;
    /**
     * Allow clients to update journal-lines.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete journal-lines.
     */
    delete?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'workspaces';
        value: string | Workspace;
      } | null)
    | ({
        relationTo: 'units';
        value: string | Unit;
      } | null)
    | ({
        relationTo: 'budgets';
        value: string | Budget;
      } | null)
    | ({
        relationTo: 'category-groups';
        value: string | CategoryGroup;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'accounts';
        value: string | Account;
      } | null)
    | ({
        relationTo: 'journal-entries';
        value: string | JournalEntry;
      } | null)
    | ({
        relationTo: 'journal-lines';
        value: string | JournalLine;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  fullName?: T;
  roles?: T;
  workspaces?:
    | T
    | {
        workspace?: T;
        roles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workspaces_select".
 */
export interface WorkspacesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  domain?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units_select".
 */
export interface UnitsSelect<T extends boolean = true> {
  workspace?: T;
  code?: T;
  name?: T;
  kind?: T;
  decimalPlaces?: T;
  symbol?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "budgets_select".
 */
export interface BudgetsSelect<T extends boolean = true> {
  workspace?: T;
  name?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category-groups_select".
 */
export interface CategoryGroupsSelect<T extends boolean = true> {
  workspace?: T;
  name?: T;
  kind?: T;
  sortOrder?: T;
  budget?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  workspace?: T;
  name?: T;
  emoji?: T;
  purpose?: T;
  isSystemDefault?: T;
  sortOrder?: T;
  categoryGroup?: T;
  budget?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  workspace?: T;
  name?: T;
  classification?: T;
  subtype?: T;
  unit?: T;
  category?: T;
  isOnBudget?: T;
  budget?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-entries_select".
 */
export interface JournalEntriesSelect<T extends boolean = true> {
  workspace?: T;
  budget?: T;
  date?: T;
  memo?: T;
  type?: T;
  status?: T;
  transferGroupId?: T;
  voidOf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-lines_select".
 */
export interface JournalLinesSelect<T extends boolean = true> {
  workspace?: T;
  entry?: T;
  account?: T;
  category?: T;
  amount?: T;
  unit?: T;
  sortOrder?: T;
  reportingAmount?: T;
  fxRate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  users?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  workspaces?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  budgets?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  categoryGroups?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  categories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  units?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  accounts?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  journalEntries?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  journalLines?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}